import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import '../../../auth/presentation/providers/auth_providers.dart';
import '../../domain/entities/product.dart';
import '../controllers/product_controller.dart';
import '../widgets/product_form_fields.dart';
import '../widgets/product_image_picker_grid.dart';

class AddProductPage extends ConsumerStatefulWidget { const AddProductPage({super.key}); @override ConsumerState<AddProductPage> createState() => _AddProductPageState(); }
class _AddProductPageState extends ConsumerState<AddProductPage> {
  final _formKey = GlobalKey<FormState>(); final _picker = ImagePicker();
  final _titleController = TextEditingController(); final _descriptionController = TextEditingController(); final _priceController = TextEditingController(); final _cityController = TextEditingController(); final _townshipController = TextEditingController(); final _addressController = TextEditingController();
  ProductCategory _category = ProductCategory.other; ProductCondition _condition = ProductCondition.used; bool _isNegotiable = false;
  @override void dispose(){ _titleController.dispose(); _descriptionController.dispose(); _priceController.dispose(); _cityController.dispose(); _townshipController.dispose(); _addressController.dispose(); super.dispose(); }
  Future<void> _pickImages() async { final picked = await _picker.pickMultiImage(imageQuality: 85, maxWidth: 1600); if(picked.isEmpty) return; ref.read(productControllerProvider.notifier).addSelectedImages(picked.map((x)=>File(x.path)).toList()); }
  Future<void> _submit() async { if(!_formKey.currentState!.validate()) return; final price = int.tryParse(_priceController.text.trim()); if(price == null) return; final id = await ref.read(productControllerProvider.notifier).createProduct(title: _titleController.text.trim(), description: _descriptionController.text.trim(), category: _category, condition: _condition, price: price, city: _cityController.text.trim(), township: _townshipController.text.trim(), address: _addressController.text.trim().isEmpty ? null : _addressController.text.trim(), isNegotiable: _isNegotiable); if(mounted && id != null) Navigator.of(context).pop(); }
  @override Widget build(BuildContext context){ final currentUser = ref.watch(currentUserProvider); final st = ref.watch(productControllerProvider); ref.listen(productControllerProvider, (previous,next){ if(!context.mounted) return; if(next.hasError) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(next.errorMessage!))); if(next.success) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Product တင်ပြီးပါပြီ'))); }); if(currentUser==null) return const Scaffold(body: Center(child: Text('Product တင်ရန် Login ဝင်ရန်လိုအပ်ပါသည်'))); return Scaffold(appBar: AppBar(title: const Text('ကုန်ပစ္စည်း တင်ရန် / Add Product')), body: AbsorbPointer(absorbing: st.isLoading, child: Form(key: _formKey, child: ListView(padding: const EdgeInsets.all(16), children: [ProductImagePickerGrid(selectedImages: st.selectedImages, isLoading: st.isUploading, onAddImage: _pickImages, onRemoveSelectedImage: (i)=>ref.read(productControllerProvider.notifier).removeSelectedImageAt(i)), const SizedBox(height:18), ProductFormFields(titleController: _titleController, descriptionController: _descriptionController, priceController: _priceController, cityController: _cityController, townshipController: _townshipController, addressController: _addressController, category: _category, condition: _condition, isNegotiable: _isNegotiable, onCategoryChanged: (v)=>setState(()=>_category=v), onConditionChanged: (v)=>setState(()=>_condition=v), onNegotiableChanged: (v)=>setState(()=>_isNegotiable=v)), const SizedBox(height:24), FilledButton.icon(onPressed: st.isLoading ? null : _submit, icon: st.isLoading ? const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)) : const Icon(Icons.add), label: const Text('ကုန်ပစ္စည်း တင်မည် / Create Product')), if(st.isUploading) ...[const SizedBox(height:12), LinearProgressIndicator(value: st.uploadProgress)] ])))); }
}
