import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import '../../../auth/presentation/providers/auth_providers.dart';
import '../../domain/entities/product.dart';
import '../controllers/product_controller.dart';
import '../providers/product_providers.dart';
import '../widgets/product_form_fields.dart';
import '../widgets/product_image_picker_grid.dart';

class EditProductPage extends ConsumerStatefulWidget { final String productId; const EditProductPage({super.key, required this.productId}); @override ConsumerState<EditProductPage> createState()=>_EditProductPageState(); }
class _EditProductPageState extends ConsumerState<EditProductPage>{
  final _formKey=GlobalKey<FormState>(); final _picker=ImagePicker(); bool _initialized=false;
  final _titleController=TextEditingController(); final _descriptionController=TextEditingController(); final _priceController=TextEditingController(); final _cityController=TextEditingController(); final _townshipController=TextEditingController(); final _addressController=TextEditingController();
  ProductCategory _category=ProductCategory.other; ProductCondition _condition=ProductCondition.used; bool _isNegotiable=false;
  @override void dispose(){_titleController.dispose();_descriptionController.dispose();_priceController.dispose();_cityController.dispose();_townshipController.dispose();_addressController.dispose();super.dispose();}
  void _initialize(Product p){ if(_initialized)return; _initialized=true; _titleController.text=p.title; _descriptionController.text=p.description; _priceController.text=p.price.toString(); _cityController.text=p.city; _townshipController.text=p.township; _addressController.text=p.address??''; _category=p.category; _condition=p.condition; _isNegotiable=p.isNegotiable; ref.read(productControllerProvider.notifier).setCurrentProduct(p); }
  Future<void> _pickImages() async{ final picked=await _picker.pickMultiImage(imageQuality:85,maxWidth:1600); if(picked.isEmpty)return; ref.read(productControllerProvider.notifier).addSelectedImages(picked.map((x)=>File(x.path)).toList());}
  Future<void> _submit() async{ if(!_formKey.currentState!.validate())return; final price=int.tryParse(_priceController.text.trim()); if(price==null)return; await ref.read(productControllerProvider.notifier).updateProduct(productId:widget.productId,title:_titleController.text.trim(),description:_descriptionController.text.trim(),category:_category,condition:_condition,price:price,city:_cityController.text.trim(),township:_townshipController.text.trim(),address:_addressController.text.trim().isEmpty?null:_addressController.text.trim(),clearAddress:_addressController.text.trim().isEmpty,isNegotiable:_isNegotiable); }
  @override Widget build(BuildContext context){ final productAsync=ref.watch(productDetailProvider(widget.productId)); final st=ref.watch(productControllerProvider); final user=ref.watch(currentUserProvider); ref.listen(productControllerProvider,(p,n){ if(!context.mounted)return; if(n.hasError)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(n.errorMessage!))); if(n.success){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Product ပြင်ပြီးပါပြီ'))); Navigator.of(context).pop();}}); return Scaffold(appBar:AppBar(title:const Text('Edit Product')),body:productAsync.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text(e.toString())),data:(p){ if(p==null)return const Center(child:Text('Product မတွေ့ပါ')); if(!p.isOwner(user?.uid??''))return const Center(child:Text('ဒီ Product ကို ပြင်ဆင်ရန် ခွင့်မရှိပါ')); _initialize(p); return AbsorbPointer(absorbing:st.isLoading, child:Form(key:_formKey, child:ListView(padding:const EdgeInsets.all(16),children:[ProductImagePickerGrid(selectedImages:st.selectedImages,existingImageUrls:st.existingImageUrls,isLoading:st.isUploading,onAddImage:_pickImages,onRemoveSelectedImage:(i)=>ref.read(productControllerProvider.notifier).removeSelectedImageAt(i),onRemoveExistingImage:(i)=>ref.read(productControllerProvider.notifier).removeExistingImageAt(i)),const SizedBox(height:18),ProductFormFields(titleController:_titleController,descriptionController:_descriptionController,priceController:_priceController,cityController:_cityController,townshipController:_townshipController,addressController:_addressController,category:_category,condition:_condition,isNegotiable:_isNegotiable,onCategoryChanged:(v)=>setState(()=>_category=v),onConditionChanged:(v)=>setState(()=>_condition=v),onNegotiableChanged:(v)=>setState(()=>_isNegotiable=v)),const SizedBox(height:24),FilledButton.icon(onPressed:st.isLoading?null:_submit,icon:st.isLoading?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save_outlined),label:const Text('Save Changes')),if(st.isUploading)...[const SizedBox(height:12),LinearProgressIndicator(value:st.uploadProgress)] ])));}));}
}
