import 'dart:io';
import 'package:flutter/material.dart';
import '../../domain/entities/chat_message.dart';

class ChatBubble extends StatelessWidget { final ChatMessage message; final String currentUserId; final VoidCallback? onDelete; const ChatBubble({super.key,required this.message,required this.currentUserId,this.onDelete}); @override Widget build(BuildContext context){final isMine=message.isMine(currentUserId); final cs=Theme.of(context).colorScheme; return Align(alignment:isMine?Alignment.centerRight:Alignment.centerLeft, child:GestureDetector(onLongPress:isMine?onDelete:null, child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:280), child:DecoratedBox(decoration:BoxDecoration(color:isMine?cs.primaryContainer:cs.surfaceContainerHighest,borderRadius:BorderRadius.circular(16)), child:Padding(padding:const EdgeInsets.all(10), child:Column(crossAxisAlignment:isMine?CrossAxisAlignment.end:CrossAxisAlignment.start, children:[if(message.isImage)_ImageContent(message:message), if(message.text.trim().isNotEmpty)...[if(message.isImage)const SizedBox(height:8),Text(message.text)], const SizedBox(height:4), Row(mainAxisSize:MainAxisSize.min,children:[Text(_timeText(message.createdAt),style:Theme.of(context).textTheme.bodySmall),const SizedBox(width:4),Icon(_statusIcon(message.status),size:14,color:message.status==ChatMessageStatus.failed?cs.error:null)])])))))); }
  String _timeText(DateTime d)=>'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';
  IconData _statusIcon(ChatMessageStatus s){switch(s){case ChatMessageStatus.sending:return Icons.schedule;case ChatMessageStatus.sent:return Icons.check;case ChatMessageStatus.delivered:return Icons.done_all;case ChatMessageStatus.read:return Icons.done_all;case ChatMessageStatus.failed:return Icons.error_outline;case ChatMessageStatus.deleted:return Icons.delete_outline;}}
}
class _ImageContent extends StatelessWidget{final ChatMessage message; const _ImageContent({required this.message}); @override Widget build(BuildContext context){Widget child; if(message.localImagePath?.trim().isNotEmpty??false){child=Image.file(File(message.localImagePath!),fit:BoxFit.cover);}else if(message.imageUrl?.trim().isNotEmpty??false){child=Image.network(message.imageUrl!,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Center(child:Icon(Icons.broken_image_outlined)));}else{child=const Center(child:Icon(Icons.image_not_supported_outlined));} return ClipRRect(borderRadius:BorderRadius.circular(12), child:SizedBox(width:220,height:180,child:child));}}
