// File generated by FlutterFire CLI.
// Updated manually to match new Firebase project: mm-market-app
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Credentials from google-services.json for project: mm-market-app
  // Project number: 805591336873
  // App ID: 1:805591336873:android:b8796af8f245e58d3a26b8
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0nILbnzaGOVoPeld7bRQ5_yTszoTh8I',
    appId: '1:805591336873:android:b8796af8f245e58d3a26b8',
    messagingSenderId: '805591336873',
    projectId: 'mm-market-app',
    storageBucket: 'mm-market-app.firebasestorage.app',
  );
}
